# Generated by Django 2.1.3 on 2018-11-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('raza', models.TextField(default='')),
                ('caracteristica', models.TextField(default='')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Rescatado', 'Rescatado'), ('Adoptado', 'Adoptado')], default='disponible', max_length=255)),
                ('imageUrl', models.ImageField(blank=True, upload_to='dog_image')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('admin', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
