# Generated by Django 2.1.3 on 2018-11-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='imageUrl',
            field=models.CharField(default='', max_length=255),
        ),
    ]
